const categories =
    [
        {id: 1, name: 'blues.jpg'},
        {id: 2, name: 'children.jpg'},
        {id: 3, name: 'classical.jpg'},
        {id: 4, name: 'comedy.png'},
        {id: 5, name: 'country.jpg'},
        {id: 6, name: 'dance.gif'},
        {id: 7, name: 'easy-listening.jpg'},
        {id: 8, name: 'electronic.png'},
        {id: 9, name: 'folk.jpg'},
        {id: 10, name: 'hip-hop.png'},
        {id: 11, name: 'industrial.png'},
        {id: 12, name: 'christian.jpg'},
        {id: 13, name: 'gospel.jpg'},
        {id: 14, name: 'jazz.jpg'},
        {id: 15, name: 'latin.jpg'},
        {id: 16, name: 'new-age.png'},
        {id: 17, name: 'opera.jpg'},
        {id: 18, name: 'pop.gif'},
        {id: 19, name: 'rnb.png'},
        {id: 20, name: 'soul.png'},
        {id: 21, name: 'reggae.jpg'},
        {id: 22, name: 'rock.jpg'},
        {id: 23, name: 'soundtrack.png'},
        {id: 24, name: 'spoken-word.png'},
        {id: 25, name: 'tejano.png'},
        {id: 26, name: 'vocal.png'},
        {id: 27, name: 'world.jpg'},
        {id: 28, name: 'punk.png'},
        {id: 29, name: 'alternative.gif'},
        {id: 30, name: 'anime.jpg'},
        {id: 31, name: 'commercial.png'},
        {id: 32, name: 'holiday.jpg'},
        {id: 33, name: 'asian.png'},
    ];

export default categories;